### ISSUE TITLE
Сделать форму заявки на собеседование

### ISSUE THREAD

**Issue by jougene** [Hexlet/hexlet-interview#12]
Поля

- Профессия (пока наверное сделаем списком, пусть вначале там отображаются те профессии которые есть на хекслете)
- Позиция (Junior, Middle, Senior)
- Имя
- Какое то описание надо, или ссылка на резюме или и то и то

**Comment by frontstall** [comment]
https://github.com/Hexlet/hexlet-interview/pull/19

**Comment by jougene** [comment]
Resolved in #19
