### ISSUE TITLE
Добавить модуль конфигурации

### ISSUE THREAD

**Issue by grigori-gru** [Hexlet/hexlet-interview#16]
Нужно добавить модуль конфигурации, если нужна работа с конфигом для орм в npm скриптах, то добавьте отдельно файл, в котором просто возвращается орм конфиг из сервиса.

**Comment by jougene** [comment]
Уже есть работа с конфигом в npm скриптах

**Comment by grigori-gru** [comment]
Так я вижу) модуля конфига нет, глянь, как у меня в форке

**Comment by jougene** [comment]
Добавить сам модуль идея хорошая ибо ее пропагандирует сам нест. Смотреть в форк странная затея, думаю хорошо будет прислать пулл реквест. Сделаешь?

**Comment by grigori-gru** [comment]
Да, хорошо
