### ISSUE TITLE
Добавить валидацию 

### ISSUE THREAD

**Issue by grigori-gru** [Hexlet/hexlet-interview#17]
Нужно добавить валидацию dto и конфига, это легко сделать как первый коммит для новичка. Через class-validator, конечно.

**Comment by jougene** [comment]
Добавить валидацию в конфиг можно, единственное я бы не стал называть это штуку ДТО, потому что немного странно выглядит.

**Comment by grigori-gru** [comment]
Я имею в виду дто на создание и обновление, они же сейчас есть уже в проекте. У конфига дто нет, конечно

**Comment by jougene** [comment]
Для создания заявки валидация добавлена, остальные валидации лучше делать в рамках конкретных фич.
