### ISSUE TITLE
Подключить сиды

### ISSUE THREAD

**Issue by jougene** [Hexlet/hexlet-interview#18]
Для того, чтобы заполнять БД тестовыми данными необходимо использовать сиды.
Нужен npm script (seed:run) который будет этим заниматься.
Предлагаю использовать https://www.npmjs.com/package/typeorm-seeding

**Comment by grigori-gru** [comment]
У себя на проекте попытался через либы с сидами работать, потом бросил, косяков куча была. В итоге сделал тестовый конфиг файл и стартовал в каждом beforeeach.

**Comment by jougene** [comment]
Какого рода были косяки?

**Comment by grigori-gru** [comment]
Со многими связями в работе проблемы были, может уже что-то поменялось, я в марте пробовал с внешними сид либами. Плюс из тех, кто на несте пишет ничего в использование такого не нашел, в основном через миграции сеют или, как я делал, в отдельном файле описывая и в коде в каждом e2e в beforeEach загружая (в рамках одной транзакции с откатом после теста здесь не получится к сожалению, issue создавал в репе nestjs, там только руками развели). На этом проекте можно в принципе поюзать, тут все проще некуда.

**Comment by mokevnin** [comment]
> Для того, чтобы заполнять БД тестовыми данными необходимо использовать сиды.

Для этого нужны фикстуры. Сиды используются для наполнения такими данными как справочники.

**Comment by grigori-gru** [comment]
Я в общем, не работало нормально с этими либами ничего, если тут получится с фикстурами-сидами, то будет прям топ, у себя потом еще раз попробую

**Comment by jougene** [comment]
Тогда пробуем вот это - https://github.com/RobinCK/typeorm-fixtures

**Comment by grigori-gru** [comment]
Что теперь с сидами-фикстурами, это актуальная задача?

**Comment by jougene** [comment]
Фикстуры подрубил, сиды пока думаю не нужны.
