### ISSUE TITLE
Добавить возможность создавать интервью

### ISSUE THREAD

**Issue by jougene** [Hexlet/hexlet-interview#27]
Интервью должны иметь возможность создавать привелигированные пользователи (типа админы).

**Comment by grigori-gru** [comment]
А как роль будет определятся, где она передается? Могу бэк взять по этой таске, через guard декоратор это  можно удобно сделать.

**Comment by jougene** [comment]
По поводу ролей пока что непонятно еще. По идее будет каким то образом заведенный пользователь-админ, у юзера будет что-то типа поле "Роль". По этой роли будет в guard'e разграничивать права.

**Comment by grigori-gru** [comment]
У меня так реализовано:
```js
@Roles(RolesEnum.MANAGER)
@Get()
async getEmployees().........
```
Но для это надо вместе при авторизации роль возвращать. А jwt вообще не стали использовать? Или еще воткнете?

**Comment by jougene** [comment]
Нам тут jwt не нужен ибо у нас простое бэкенд приложение, без клиент-серверного взаимодействия

**Comment by jougene** [comment]
Пока не берите эту задачу. Возможно все изменится.

**Comment by mput** [comment]
Хочу взять.
Реализация примерно следующая. 
Для админа, на странице заявок - будут кнопки "назначить интервью" возле заявок, которые ведут в интерфейс, в котором можно создать/выбрать из списка интервьюера, и указать дату.
Над деталями подумаю в процессе. 
@jougene что скажешь?

**Comment by jougene** [comment]
Давай, только предлагаю для начала тебе набросать интерфейс и скрины приложить, чтобы примерно понимать как оно будет

**Comment by mput** [comment]
Да, конечно.
Тогда, задачу взял.:)

**Comment by jougene** [comment]
UPD. В названии задачи неточность - щас это скорее звучит - добавить админу возможность подтверждать интервью и назначать собеседующего
