### ISSUE TITLE
Добавить данные по уже прошедшим онлайн интервью

### ISSUE THREAD

**Issue by jougene** [Hexlet/hexlet-interview#28]
Накатываем миграцией в БД, данные берем отсюда
- https://www.youtube.com/watch?v=YrXJzD2E6NU&list=PLo6puixMwuSOa_0EH6X4OXzFAmyQGS3a3

**Comment by mput** [comment]
Присоединюсь к вам, начну отсюда, если никто не против.

Кажется что тащить что то вроде https://github.com/w3tecch/typeorm-seeding пока лишнее, сделаю просто через миграцию, данные добавлю в JSON.

**Comment by jougene** [comment]
Сиды тут и не нужны. Про JSON  не понял - о чем речь?
