### ISSUE TITLE
Подкорректировать тесты

### ISSUE THREAD

**Issue by grigori-gru** [Hexlet/hexlet-interview#29]
Тесты как-то странно сделаны: 
1) они не независимые, каждый тест хранит в себе информацию о предыдущем вызове, если у вас добавление в базу в beforeEach, значит в конце данных будет столько, сколько тестов запустили
2) зачем у вас всё в одну кучу в инициализации тестового [app](https://github.com/Hexlet/hexlet-interview/blob/master/test/app.testing.ts#L20). Это никак не упрощает ничего, почему репозиторий с которым в конкретном тесте работаете нельзя вызвать. Зачем-то close, getHttpServer переопределяется. Здесь можно просто фикстуры общие подгрузить и возвращать обычный инстанс nest app. Плюс тип если указать явно для app в  'Authorization test', то он тоже ругаться начнет на entity.
3) ставьте в каждом тесте async/await при работе с реквестом, стартуйте jest с detectOpenHandles, он вам об этом укажет. 
4) хз как с sqlite этим, но с pg я все тесты через --runInBand запускал, это обеспечивало последовательное выполнение и все возможные конфликты при работе с базой устраняло, может с sqlite проще, хотя с ним постоянно `Sqlite does not support AUTOINCREMENT on composite primary key` при попытке запуска с synchronize происходит.

**Comment by jougene** [comment]
Кое что пофиксил.

**Comment by jougene** [comment]
Непонятно кстати с какой целью ты локальные тесты у себя запускаешь не так как другие и пользуешься постгресом.

**Comment by grigori-gru** [comment]
Это про проект на работе, в нашем случае всё с sqlite стартую, хотя если бы не требования этого проекта, то выкинул бы её и не вспоминал, не вижу какого-то супер упрощения в работе с ней, скорее какие-то непредсказуемые поведения, баги.
