### ISSUE TITLE
Dev config

### ISSUE THREAD

**Issue by grigori-gru** [Hexlet/hexlet-interview#32]
[Получается](https://github.com/Hexlet/hexlet-interview/blob/9a7999695c13bb991c00f96ae7cb279cf2ed98d3/src/modules/config/config.service.ts#L33
), что теперь в дев режиме можно только sqlite можно стартовать что ли?

Если нам понадобится валидация конфига, то как мы будем через process.env валидировать?
У нас теперь вообще ничего нельзя добавить в конфиге, все в коде зашито

**Comment by jougene** [comment]
Вернул пока что так, ибо то как нест предлагает работать с энв файлами не подходит для работы приложения на проде. Я уже писал, что тот пр сломал релиз.

**Comment by jougene** [comment]
По поводу sqlite в дев и тест режимах - так сделано специально, чтобы не приходилось дополнительно поднимать базу в докере, тк это накладывает дополнительные сложности в первоначальной настройке

**Comment by grigori-gru** [comment]
Да каждый может, как хочет сделать, есть же сетап для упрощения, он по дефолту в development.env идет

**Comment by grigori-gru** [comment]
А как в хероку какой файл конфигурации? Я этот момент не учел, конечно...

**Comment by jougene** [comment]
> А как в хероку какой файл конфигурации? Я этот момент не учел, конечно...

В хероку нет такого, что есть энв файлы. Переменные окружения передаются в приложение как настоящие переменные окружения. Для работы с БД есть DATABASE_URL. Нету переменных типа DB_TYPE и так далее.

**Comment by jougene** [comment]
>Я этот момент не учел, конечно...

Бывает, но в этом есть и моя вина, что я это также не учел.

**Comment by jougene** [comment]
В случае работы с докером по-честному - также не будут энв файлы, переменные окружения также будут браться извне по отношению к контейнеру, и поэтому мы должны уметь читать не уже провалидированные конфиг а сырые переменные окружения. Так что момент с валидацией конфига после считывания файла я считаю сомнительной затеей.

**Comment by grigori-gru** [comment]
О, у нас в этом смысле проще на уровне кода, через шаблоны генерится конфиг в json c данными среды и с ним уже в проекте работаю. То есть .env как таковые не юзаю в самом проекте, просто использую config.[node_env].json и с валидацией в этом контексте удобнее
