### ISSUE TITLE
Добавить вход через github

### ISSUE THREAD

**Issue by jougene** [Hexlet/hexlet-interview#37]

**Comment by mput** [comment]
Я возьмусь, если никто еще не делает.

**Comment by mput** [comment]
У нас сейчас поля у User - firstname и lastname - обязательные. На GitHub во-первых есть только поле name, во-вторых оно может быть пустым.
Как поступим:
1.  Сделать эти поля не обязательными при входе через социальный профиль, с возможностью до заполнить после.
2. При входе через GH при создании нового профиля перекидывать на страницу с вводом имени, и создавать профиль только после ввода этих данных. 
??

**Comment by jougene** [comment]
давай пойдем по второму пути и посмотрим что получится)

**Comment by mput** [comment]
Второй путь мне показался через чур усложненным. Сделал немного по другому, скоро будет PR. Потом будем уже по коду обсуждать.
