### ISSUE TITLE
Исправить поведение при успешной регистрации.

### ISSUE THREAD

**Issue by jougene** [Hexlet/hexlet-interview#39]
В данный момент после успешной регистрации прямо в браузер отдается джсон с полной моделью юзера. 
Необходимо сделать так, чтобы выводилось флеш-сообщение об успешной регистрации и происходил редирект на страницу с входом.

**Comment by mput** [comment]
Возьму.

**Comment by jougene** [comment]
Ее уже взял @mitry1974, сорри что так получилось)

**Comment by mput** [comment]
Не проблема. Может кстати редиректить не на страницу с входом, а уже на главную в авторизованном состоянии?

**Comment by jougene** [comment]
Может даже и так. )
