### ISSUE TITLE
Добавить подтверждение email при регистрации

### ISSUE THREAD

**Issue by jougene** [Hexlet/hexlet-interview#41]

**Comment by grigori-gru** [comment]
Возьму

**Comment by grigori-gru** [comment]
Хочу создать таблицу отдельную для подтверждения пароля и добавить поле `verified` в сущность User. Потом при регистрации пользователя будет сгенерирована ссылка с  uuid на `/auth/verified/:token`, отпралена на почту пользователя для подтверждения, после перехода сущность подтверждения удаляется, `verified` меняется. Ок? Или какие-то еще варианты? Откуда у нас отправление почты будет, это как-то в конфиге нужно указать?

Всё хочу собираюсь сделать на подобие того, как [здесь](https://github.com/marcomelilli/nestjs-email-authentication) реализовано

**Comment by jougene** [comment]
> Откуда у нас отправление почты будет, это как-то в конфиге нужно указать?

Будет переменная окружения, что-то типа `EMAIL_FROM` прописанная на хероку. В первое время предлагаю использовать https://mailtrap.io/ для тестирования.

**Comment by jougene** [comment]
>Хочу создать таблицу отдельную для подтверждения пароля

А отдельная таблица зачем? Давай в юзера засунем все и все.
Ну типа можно и так и так, просто я бы не создавал новую сущность.

**Comment by grigori-gru** [comment]
Давай в одной сущности, без проблем, если уж слишком в pr избыточно будет выглядеть - поменяю

**Comment by grigori-gru** [comment]
Я сейчас pr сделаю без самой отправки письма, она в отдельном модуле будет, я все укажу. Здесь будет общая логика переделано, тесты добавлены. Пока не понял, куда редирект должен происходить.

**Comment by grigori-gru** [comment]
В любом случае на сервис отправки у нас мока будет в тестах

**Comment by grigori-gru** [comment]
У нас в кофниг тогда эти параметры будут добавлены:
MAIL_HOST
MAIL_PORT
MAIL_USER
MAIL_PASSWORD
MAIL_FROM

**Comment by grigori-gru** [comment]
Здесь что-то еще нужно доделать?

**Comment by jougene** [comment]
Нет, можно закрывать.
