### ISSUE TITLE
Переход на ESLint и Airbnb Style Guide?

### ISSUE THREAD

**Issue by mput** [Hexlet/hexlet-interview#44]
Судя по всему TSlint скоро [задеприкейтят](https://github.com/palantir/tslint/issues/4534). Может быть перейдем на ESlint с Airbnb, пока кода еще немного, и не сложно будет откорректировать?

**Comment by grigori-gru** [comment]
Команда TS с 3.7 версии переходит на eslint. Он 100% лучше)

**Comment by 1ike** [comment]
Тогда можно будет и от prettier отказаться, наверное - eslint вроде как нормально фиксит?

**Comment by grigori-gru** [comment]
Не, зачем его убирать? Они нормально друг с другом работают

**Comment by mput** [comment]
Сделаю, очень хочу eslint :).

**Comment by 1ike** [comment]
Ну, когда есть только tslint, то альтернативы prettier нет, т.к. форматирует tslint отвратно. А eslint, судя по js, норм форматирует. К связке tslint+prettier особых претензий не было, но бесило, что не было возможности две пустые строки после импортов ставить.
