### ISSUE TITLE
Валидация дто в контроллере

### ISSUE THREAD

**Issue by grigori-gru** [Hexlet/hexlet-interview#46]
Зачем [валидацию](https://github.com/Hexlet/hexlet-interview/blob/b528876c4bca11a6e37f8eab6bd8be1f193ffadc/src/modules/auth/auth.controller.ts#L25
) дто выносить на уровень контроллера?

**Comment by jougene** [comment]
ЕМНИП там надо было писать кастомный валидатор для сравнения двух полей в одном классе, и решили пока сделать так. Если есть уже готовое решение, которое это делает, то присылай pull request
