### ISSUE TITLE
Добавлен joi, когда уже есть class-validator

### ISSUE THREAD

**Issue by grigori-gru** [Hexlet/hexlet-interview#47]
Зачем нужен еще один валидатор, когда уже другой используется? Конечно, в доке есть пример, где `joi` юзается, но там тоже спокойно можно одним валидатором обойтись.

**Comment by jougene** [comment]
Давай мы не будем создавать ишью с вопросами, а в случае какого несоответствия или предложения делать сразу ПР с исправлением. В данном случае https://github.com/Hexlet/hexlet-interview/blob/9fff2355369148b38bbd20f4e68296803c67d7ce/src/modules/auth/auth.controller.ts#L7 выглядит просто как лишний импорт

**Comment by grigori-gru** [comment]
Да я не понял, раз указывают в импорте его и в коммите, значит собираются использовать?

**Comment by jougene** [comment]
О каком коммите речь? В любом случае - это недосмотр на ревью, за всем не уследишь. Но щас по сути можно убрать.

**Comment by grigori-gru** [comment]
Это в мастере было актуальном, я начал по своей таске работать и увидел. Можно что-то типа no-unused добавить в линтер, чтобы избежать неиспользуемых параметров в импортах

**Comment by jougene** [comment]
кажется больше неактуально
