### ISSUE TITLE
Лучше использовать декораторы nestjs, там где это возможно

### ISSUE THREAD

**Issue by grigori-gru** [Hexlet/hexlet-interview#48]
Тут хотел бы обсудить, это моё скорее мнение, если есть возможность, то лучше использовать декораторы. На примере [`redirect`](https://github.com/Hexlet/hexlet-interview/blob/master/src/modules/auth/auth.controller.ts#L35), смысл его использовать, если можно поставить `@Redirect('/auth/sign_in')` сразу? Это выразительней, как мне кажется, не нужно res дергать лишний раз, плюс ответственность не размывается. Я его у себя стараюсь уж совсем в крайних случаях вытаскивать. На тот же flash можно декоратор сделать, будет хорошим стартовым issue)

**Comment by jougene** [comment]
Ждем пр.

**Comment by grigori-gru** [comment]
Это все просто топ для первого pr, там чисто декоративные изменения
