### ISSUE TITLE
Перейти на постгрес для test & development

### ISSUE THREAD

**Issue by jougene** [Hexlet/hexlet-interview#50]
- Пусть пока бд запускается в докер-композ
- Приложение стартует локально
- Поправить конфиг чтобы работало с переменными окружения

**Comment by mput** [comment]
Возьму

**Comment by jougene** [comment]
Возможно придется подрутить тесты, тк это раньше было в sqlite и использовался memory adapter. Сейчас нужно позаботиться об оборачивания тестов в транзакции и откатов.

**Comment by grigori-gru** [comment]
О, наконец-то!
