### ISSUE TITLE
Добавить strictNullChecks

### ISSUE THREAD

**Issue by grigori-gru** [Hexlet/hexlet-interview#53]
Давайте добавим `strictNullChecks: true` в `tsconfig`. У нас много мест, где при выборке может возвращаться undefined, но это никак не проверяется, типы нам помогают в этом. Странно, что сразу не ввели.

**Comment by jougene** [comment]
Давай.

**Comment by grigori-gru** [comment]
Там изменений будет очень много

**Comment by grigori-gru** [comment]
Давай наверное хотя бы с регистрацией закончим и я сделаю pr с этими изменениями

**Comment by grigori-gru** [comment]
Давайте теперь за это возьмусь
