### ISSUE TITLE
Добавить возможность просматривать свой список заявок

### ISSUE THREAD

**Issue by jougene** [Hexlet/hexlet-interview#64]
После того, как человек оставил заявку у него нет возможности просмотреть и отредактировать свою заявку. Необходимо добавить страницу с профилем и возможностью просмотра списка заявок.
Возможно после оставления заявок есть смысл редиректить на эту страницу.

**Comment by mput** [comment]
Фронт прям брать из cv.hexlet.io по максимуму, должно быть похоже.

**Comment by mput** [comment]
взял
